<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Predicting Solar Power Supply Generation in the Philippines using Deep Learning">

<title>Sandro Luis R. Silva - Here Comes The Sun</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/profile.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-9FYFKWYLVG"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-9FYFKWYLVG', { 'anonymize_ip': true});
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Sandro Luis R. Silva - Here Comes The Sun">
<meta name="twitter:description" content="Predicting Solar Power Supply Generation in the Philippines using Deep Learning">
<meta name="twitter:image" content="source-files/thumbnail.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sandro Luis R. Silva</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html" rel="" target="">
 <span class="menu-text">Resume</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/slrsilva/slrsilva.github.io" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Here Comes The Sun</h1>
                  <div>
        <div class="description">
          Predicting Solar Power Supply Generation in the Philippines using Deep Learning
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">python</div>
                <div class="quarto-category">machine-learning</div>
                <div class="quarto-category">deep-learning</div>
                <div class="quarto-category">lstm</div>
                <div class="quarto-category">energy</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">Apr 25, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p><img src="source-files/thumbnail.png" class="img-fluid" style="width:100.0%"></p>
<section id="sec-authors" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="sec-authors"><span class="header-section-number">1</span> Authors</h2>
<p>This analysis was done together with my groupmate Jac Lin T. Yu</p>
<p>Original creation and submission of this report was last Dec 2019.</p>
</section>
<section id="sec-executivesummary" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-executivesummary"><span class="header-section-number">2</span> Abstract</h2>
<div class="executive-summary">
<p>Due to the increasing focus towards sustainable global efforts against climate change, renewable energy generation, more specifically solar power generation, has experienced a significant growth in the past few years. However, solar power production by nature is still considered highly volatile and intermittent, due to its high dependency on various factors such as irridiation, cloud cover, temperature, and other weather parameters. As such, the inherent volatile nature of solar poses significant challenges in accurate forecasting techniques not only to solar power plant operators but also to power grid operators. This paper provides a deep learning model approach in forecasting solar power production with multiple weather variables</p>
<p>In the paper, four sites across the Philippines were considered, and four variations of the LSTM model were implemented. For two power plants, the best model had a single layer (32-nodes) LSTM, while the other two, utilized a two layer LSTM model with 64 and 32 nodes. The modifed Mean Absolute Error across all four sites reduced by at least 60% when compared to industry standard.</p>
</div>
<p><br><br></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="source-files/Poster.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</section>
<section id="sec-introduction" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-introduction"><span class="header-section-number">3</span> Introduction</h2>
<p>With the increasing devastating e ects of climate change, governments and industries have long been developing policies to mitigate its impact. In the COP21 or the 2015 Paris Climate Conference, all participating countries have agreed to reduce carbon emission in order to contain global warming to below 2°C. In addition, the United Nation’s 2030 Sustainable Development Goals which aims to address various societal issues, include provisions to produce affordable and clean energy (SDG 7) and provide climate action (SDG 13). Thus, the global energy industry has veered its focus away from traditional fuel sources to renewable and sustainable solutions, such as hydroelectric, solar and wind.</p>
<section id="sec-statement-of-the-problem" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="sec-statement-of-the-problem"><span class="header-section-number">3.1</span> Statement of the Problem</h3>
<p>The shift towards renewable energy poses new threats and challenges to existing power grids across the world due to the inherent variability and intermittency of solar power. The problem then is “Using neural networks, can solar power generation be predicted better than what industry currently uses given weather data?”</p>
</section>
<section id="sec-significance" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="sec-significance"><span class="header-section-number">3.2</span> Significance</h3>
<p>Accurate forecasting of solar power can help solar power plant operators reduce the risk of unnecessary market penalties. In addition, forecasting accurate solar power generation may provide power grid operators the ability to balance and schedule the distribution of generated power, for not only renewable power operators, but also conventional (and rigid) power plants, such as coal and natural gas. The overall significance of this study is to ensure a more secure and stable power grid even with high solar power penetration.</p>
</section>
<section id="sec-scope" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="sec-scope"><span class="header-section-number">3.3</span> Scope and Limitation</h3>
<p>The study only considers four solar power plants located in North Luzon, Greater Metro Manila, Visayas. No plants in the South Luzon and Mindanao regions were considered. Only 2 years and 8 months worth of weather data was included in the study. This data, however, does not include solar irridiance, an important indicator of solar power generation, due to the lack of availability.</p>
</section>
</section>
<section id="sec-proposed-framework" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-proposed-framework"><span class="header-section-number">4</span> Proposed Framework</h2>
<section id="sec-lstm" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="sec-lstm"><span class="header-section-number">4.1</span> Long-Short Term Memory</h3>
<div id="fig-lstm" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="source-files/LSTM_Cell.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Architecture of an LSTM Cell.</figcaption><p></p>
</figure>
</div>
<p>Long Short Term Memory, or also known as LSTM, is a deep learning method proposed in 1997 to address the vanishing or exploding gradient problem encountered in Recurrent Neural Networks when dealing with time series forecasting <span class="citation" data-cites="1">(<a href="#ref-1" role="doc-biblioref">Zhang, Chi, and Xiao 2018</a>)</span>. It is a type of recurrent neural network (RNN) that can learn long-term dependencies between time steps of sequence data. It does this by integrating a memory cells, also known as gates, that allows the learning of complex and long-term temporal dynamics of the data <span class="citation" data-cites="2">(<a href="#ref-2" role="doc-biblioref">Qing and Niu 2018</a>)</span>. <a href="#fig-lstm">Figure&nbsp;1</a> shows the gates mechanism that allows the interaction of the memory cell <span class="citation" data-cites="3">(<a href="#ref-3" role="doc-biblioref">Rassem, El-Beltagy, and Saleh 2017</a>)</span>.</p>
<p>These “gates” determine which unimportant data should be forgotten and which important feature should be remembered. These gates are typically composed on sigmoid neural net layers and a pointwise multiplication operation. There are three gates in a typical LSTM: forget gate, input gate, and output gate.</p>
<p><span id="eq-lstm-it"><span class="math display">\[
    \vec{i}_t=\sigma(\vec{W}_{xi}\vec{x}^{t}+\vec{W}_{hi}\vec{h}^{(t-1)}+\vec{b}_i)
\tag{1}\]</span></span></p>
<p><span id="eq-lstm-gt"><span class="math display">\[
    \vec{g}_t=tanh(\vec{W}_{xg}\vec{x}^{t}+\vec{W}_{hg}\vec{h}^{(t-1)}+\vec{b}_g)
\tag{2}\]</span></span></p>
<p><span id="eq-lstm-ft"><span class="math display">\[
    \vec{f}_t=\sigma(\vec{W}_{xf}\vec{x}^{t}+\vec{W}_{hf}\vec{h}^{(t-1)}+\vec{b}_f)
\tag{3}\]</span></span></p>
<p><span id="eq-lstm-ot"><span class="math display">\[
    \vec{o}_t=\sigma(\vec{W}_{xo}\vec{x}^{t}+\vec{W}_{ho}\vec{h}^{(t-1)}+\vec{b}_o)
\tag{4}\]</span></span></p>
<p><span id="eq-lstm-ct"><span class="math display">\[
    \vec{C}^t=(\vec{C}^{(t-1)}\odot\vec{f}_{t})\oplus(\vec{i}_{t}\odot\vec{g}_{t})
\tag{5}\]</span></span></p>
<p><span id="eq-lstm-ht"><span class="math display">\[
    \vec{h}_t=\vec{o}_{t}\odot tanh(\vec{C}_{t})
\tag{6}\]</span></span></p>
<p>The input gate (<span class="math inline">\(i_t\)</span>) seen in <a href="#eq-lstm-it">Equation&nbsp;1</a> and input modulation gate (<span class="math inline">\(g_t\)</span>) seen in <a href="#eq-lstm-gt">Equation&nbsp;2</a>, where <span class="math inline">\(\vec{W}\)</span> are the weights matrices and <span class="math inline">\(\vec{b}\)</span> are the bias terms, allows the updating of the cell.</p>
<p><a href="#eq-lstm-ft">Equation&nbsp;3</a> shows the computation of the forget gate (<span class="math inline">\(f_t\)</span>) which determines if the information is suppressed or allowed to pass through and <a href="#eq-lstm-ot">Equation&nbsp;4</a> shows the computation of the output gate (<span class="math inline">\(o_t\)</span>) which decides how the hidden states are updated.</p>
<p>At the current time step (<span class="math inline">\(t\)</span>), the cell is updated by <a href="#eq-lstm-ct">Equation&nbsp;5</a> and the values of the hidden units are updated by <a href="#eq-lstm-ht">Equation&nbsp;6</a></p>
</section>
<section id="sec-evaluation" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="sec-evaluation"><span class="header-section-number">4.2</span> Evaluation Metric</h3>
<p>Traditionally, researchers utilized classical statistical indicators used in solar power forecasting, specically the Mean Absolute Error, or also known as <span class="math inline">\(MAE\)</span>, as mentioned by<span class="citation" data-cites="4">(<a href="#ref-4" role="doc-biblioref">Wang, Qi, and Liu 2019</a>)</span> and <span class="citation" data-cites="5">(<a href="#ref-5" role="doc-biblioref">Sobri, Koohi-Kamali, and Rahim 2018</a>)</span>. The <span class="math inline">\(MAE\)</span> refers to the average distance between the measured values and forecasting model. This analysis is appropriate to evaluate uniform prediction errors.</p>
<p><span id="eq-mae"><span class="math display">\[
  MAE = \frac{1}{N} \sum_{n=1}^{N} | P_{pred}-{P_{act} |}
\tag{7}\]</span></span></p>
<p>where <span class="math inline">\(P_{pred}\)</span> defines the predicted energy generation by the model and <span class="math inline">\(P_{act}\)</span> defines the actual energy generation</p>
<p>However, the <span class="math inline">\(MAE\)</span> fails to consider power grid elements and requirements. It is therefore important to utilize performance metrics that asses power generation forecasting by considering various forecast time-scales, and capacity restrictions. In addition, <span class="citation" data-cites="5">Sobri, Koohi-Kamali, and Rahim (<a href="#ref-5" role="doc-biblioref">2018</a>)</span> indicated that depending on the use case, metrics assessments can be classified into four types i.e., statistical, ramp characterization, uncertainty quantification, and economic metrics. As such, <span class="citation" data-cites="6">Almeida, Perpiñán, and Narvarte (<a href="#ref-6" role="doc-biblioref">2015</a>)</span>, implemented a modified <span class="math inline">\(MAE\)</span>, defined as cvMAE, which evaluates a model by that penalize the hourly or daily energy error. The <span class="math inline">\(cvMAE\)</span> measures the goodness of the predictions for applications requiring hourly predictions during a period of a day. <span class="citation" data-cites="6">(<a href="#ref-6" role="doc-biblioref">Almeida, Perpiñán, and Narvarte 2015</a>)</span></p>
<p><span id="eq-cvmae"><span class="math display">\[
cvMAE = \frac{MAE}{P_{mean}}
\tag{8}\]</span></span></p>
<p>where <span class="math inline">\(P_{mean}\)</span> defines the mean of measured power in a given time-horizon.</p>
<p>In this study, a modified version of the <span class="math inline">\(MAE\)</span> and <span class="math inline">\(cvMAE\)</span> will be utilized. The proposed metric takes into consideration not only classical statistical error measurement observed in the <span class="math inline">\(MAE\)</span>, but also energy industry related considerations, such as day-ahead projected generation and rated capacity of each specific plant, labeled as <span class="math inline">\(mMAE\)</span></p>
<p><span id="eq-mmae"><span class="math display">\[
mMAE = \frac{\frac{1}{N} \sum_{n=1}^{N} | P_{pred}-{P_{act} |}}{P_{max}}=\frac{MAE}{P_{max}}
\tag{9}\]</span></span></p>
<p>where <span class="math inline">\(P_{max}\)</span> indicates a solar power plant’s peak installed capacity, or the intended full-load sustained output of the power plant.</p>
</section>
</section>
<section id="sec-methodology" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sec-methodology"><span class="header-section-number">5</span> Methodology</h2>
<section id="sec-dataset" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="sec-dataset"><span class="header-section-number">5.1</span> Dataset</h3>
<p>From December 26, 2016 to August 25, 2019, energy generation data in megawatts (MW) was collected from the Philippines’ Wholesale Electricity Spot Market (WESM). To limit the scope of the study, only four solar power plants located across Luzon and Visayas were chosen. One power plant was selected per location/province. <a href="#tbl-pp">Table&nbsp;1</a> shows these plants along with their location and rated dependable capacity, a metric that refers to the maximum amount of power that a power plant can produce over a specified period of time, while <a href="#tbl-pp-dict">Table&nbsp;2</a> shows a data dictionary of the collected data.</p>
<div id="tbl-pp" class="anchored">
<table class="table">
<caption>Table&nbsp;1: Summary of selected power plants, location, and capacity</caption>
<thead>
<tr class="header">
<th>Power Plant</th>
<th>Location</th>
<th>Capacity (in MW)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Clark Solar Power Plant</td>
<td>Mabalacat, Pampanga</td>
<td>22 MW</td>
<td></td>
</tr>
<tr class="even">
<td>First Toledo Solar Power Plant</td>
<td>Toledo, Cebu</td>
<td>60 MW</td>
<td></td>
</tr>
<tr class="odd">
<td>Subic Solar Power Plant</td>
<td>Olongapo, Zambales</td>
<td>100 MW</td>
<td></td>
</tr>
<tr class="even">
<td>Valenzuela Solar Power Plant</td>
<td>Valenzuela, NCR</td>
<td>8.5 MW</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-pp-dict" class="anchored">
<table class="table">
<caption>Table&nbsp;2: Data Dictionary of the WESM data</caption>
<thead>
<tr class="header">
<th>Name</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DATETIME</td>
<td>Delivery datetime (ex. 12/26/2016 12:00:00 AM)</td>
</tr>
<tr class="even">
<td>YEAR</td>
<td>Datetimelike Property for the Specific Year in the Datetime</td>
</tr>
<tr class="odd">
<td>MONTH</td>
<td>Datetimelike Property for the Specific Month in the Datetime</td>
</tr>
<tr class="even">
<td>DAY</td>
<td>Datetimelike Property for the Specific Day in the Datetime</td>
</tr>
<tr class="odd">
<td>HOUR</td>
<td>Datetimelike Property for the Hour/Interval in the Datetime</td>
</tr>
<tr class="even">
<td>RESOURCE_ID</td>
<td>Each power plant and unit has a specific ID</td>
</tr>
<tr class="odd">
<td>MW</td>
<td>Registered MW generated for the spefic hour</td>
</tr>
</tbody>
</table>
</div>
<p>Corresponding weather data, in each of these four locations, were collected separately from the Weather Underground website. The weather data contained 10 features. A data dictionary of the collected data can be seen in <a href="#tbl-weather">Table&nbsp;3</a>.</p>
<div id="tbl-weather" class="anchored">
<table class="table">
<caption>Table&nbsp;3: Data Dictionary of the Weather data from the Weather Underground Website</caption>
<thead>
<tr class="header">
<th>Name</th>
<th>Unit of Measure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Temperature</td>
<td>degrees Fahrenheit</td>
</tr>
<tr class="even">
<td>Humidity</td>
<td>percentage</td>
</tr>
<tr class="odd">
<td>Dew Point</td>
<td>degrees Fahrenheit</td>
</tr>
<tr class="even">
<td>Pressure</td>
<td>inches</td>
</tr>
<tr class="odd">
<td>Precipitation</td>
<td>inches</td>
</tr>
<tr class="even">
<td>Cumulative Precipitation</td>
<td>inches</td>
</tr>
<tr class="odd">
<td>Wind Speed</td>
<td>mph</td>
</tr>
<tr class="even">
<td>Wind Gust</td>
<td>mph</td>
</tr>
<tr class="odd">
<td>Wind Direction</td>
<td>direction of wind</td>
</tr>
<tr class="even">
<td>Weather Condition</td>
<td>conditional</td>
</tr>
</tbody>
</table>
</div>
<p>Granularity of the data is in 1-hr intervals, which results in a total of 23160 observations per plant. The experiment implemented a 80-10-10 training, validation and test split.</p>
</section>
<section id="sec-models" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="sec-models"><span class="header-section-number">5.2</span> Models</h3>
<section id="sec-industrybenchmark" class="level4" data-number="5.2.1">
<h4 data-number="5.2.1" class="anchored" data-anchor-id="sec-industrybenchmark"><span class="header-section-number">5.2.1</span> Industry Benchmark</h4>
<p>For the industry benchmark, <span class="math inline">\(P_{pred}\)</span> is defined as each solar power plant’s day-ahead hourly projection submission to the market operator (in this case <span class="math inline">\(T_{t-24}\)</span> hours), and <span class="math inline">\(P_{act}\)</span> is defined as the actual scheduled dispatch by the solar plant considering the market operator’s dispatching schedule. The comparison between the <span class="math inline">\(P_{pred}\)</span> and the <span class="math inline">\(P_{act}\)</span> were examined.</p>
</section>
<section id="sec-proposed" class="level4" data-number="5.2.2">
<h4 data-number="5.2.2" class="anchored" data-anchor-id="sec-proposed"><span class="header-section-number">5.2.2</span> Proposed Models</h4>
<p>Four proposed models were utilized in this study all focusing on the LSTM neural network. Networks 1 and 2 considered a single LSTM layer with nodes, 64 and 32 respectively, while networks 3 and 4 considered a stacked two layer LSTM network with nodes 64-32 and 32-64 respectively.</p>
<p>An additional feed-forward hidden layer with a rectified linear unit activation function was utilized at the end of all four networks, where the number of hidden nodes corresponded to the number of hidden nodes of the last LSTM layer.</p>
<p>Network 1 and 4 utilized 32 nodes, while networks 2 and 3 utilized 64 nodes. All four networks considered the <code>optimizer=RMSProp</code>, <code>dropouts=0.2</code> and <code>recurrent dropouts=0.2</code>, <code>batch size=128</code>, and an <code>epoch setting=50</code>.</p>
</section>
</section>
</section>
<section id="sec-results" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-results"><span class="header-section-number">6</span> Results</h2>
<div id="tbl-results" class="anchored">
<table class="table">
<caption>Table&nbsp;4: Summary of Benchmark vs Model Performances</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Power Plant</th>
<th>Best Model</th>
<th>Industry Benchmark Model</th>
<th>Performance Improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Clark Solar Power Plant</td>
<td>LSTM+LSTM with 32 &amp; 64 nodes</td>
<td>2.86%</td>
<td>12.01%</td>
</tr>
<tr class="even">
<td>First Toledo Solar Power Plant</td>
<td>LSTM with 32 nodes</td>
<td>4.30%</td>
<td>15.34%</td>
</tr>
<tr class="odd">
<td>Subic Solar Power Plant</td>
<td>LSTM with 32 nodes</td>
<td>1.36%</td>
<td>3.64%</td>
</tr>
<tr class="even">
<td>Valenzuela Solar Power Plant</td>
<td>LSTM+LSTM with 32 &amp; 64 nodes</td>
<td>2.58%</td>
<td>12.48%</td>
</tr>
</tbody>
</table>
</div>
<p>Table 2 shows the results of for each location. The stacked 2 layer LSTM with 32 and 64 nodes is the best performing model for the Clark Solar Power Plant and the Valenzuela Solar Power Plant, whereas the single layer LSTM model with 32 nodes best ts the First Toledo Solar Power Plant and the Subic Solar Power Plant.</p>
<p>For the Clark Solar Power Plant, the initial industry benchmark error was computed at 12.01%, and the 2 layer LSTM with 32 and 64 nodes model error is at 2.86%, which translates to a 76.19% error reduction.</p>
<p>For the First Toledo Solar Power Plant, a 15.34% industry benchmark error was computed, and the single layer LSTM with 32 nodes model produced only a 4.30% model error, which translates to a 71.97% error reduction.</p>
<p>For the Subic Solar Power Plant, the initial industry benchmark error was computed at 3.64%, and the single layer LSTM with 32 nodes model error is at 1.36%, which translates to a 62.64% error reduction.</p>
<p>For the Valenzuela Solar Power Plant, a 12.48% industry benchmark error was computed, and the two layer LSTM with 32 and 64 nodes model produced only a 2.58% model error, which translates to a 71.33% error reduction.</p>
</section>
<section id="sec-conclusions" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="sec-conclusions"><span class="header-section-number">7</span> Conclusions &amp; Recommendations</h2>
<p>Improvements brought upon by the utilization of deep learning models can reduce costs for both suppliers and the national grid operators, and increase the effciency of power generation.</p>
<p>Further studies can be conducted using di erent neural network architectures, varying numbers of nodes, layers, and optimizers of the LSTM layer, adding dense layers with different nodes. Including data that are main drivers of solar power generation, such as quality and angle of solar panels and the hourly irridiance, can drastically improve results.</p>
<p>A study that produces one model for all solar power plants may also be considered. Location and descriptors of the power plant can be included which is fed to a CNN network together with an LSTM model will consider both spatio-temporal features.</p>
</section>
<section id="sec-references" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="sec-references"><span class="header-section-number">8</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-6" class="csl-entry" role="listitem">
Almeida, Marcelo Pinho, Oscar Perpiñán, and Luis Narvarte. 2015. <span>“PV Power Forecast Using a Nonparametric PV Model.”</span> <em>Solar Energy</em> 115: 354–68. https://doi.org/<a href="https://doi.org/10.1016/j.solener.2015.03.006">https://doi.org/10.1016/j.solener.2015.03.006</a>.
</div>
<div id="ref-2" class="csl-entry" role="listitem">
Qing, Xiangyun, and Yugang Niu. 2018. <span>“Hourly Day-Ahead Solar Irradiance Prediction Using Weather Forecasts by LSTM.”</span> <em>Energy</em> 148: 461–68. https://doi.org/<a href="https://doi.org/10.1016/j.energy.2018.01.177">https://doi.org/10.1016/j.energy.2018.01.177</a>.
</div>
<div id="ref-3" class="csl-entry" role="listitem">
Rassem, Aliaa, Mohammed A. El-Beltagy, and Mohamed Saleh. 2017. <span>“Cross-Country Skiing Gears Classification Using Deep Learning.”</span> <em>ArXiv</em> abs/1706.08924.
</div>
<div id="ref-5" class="csl-entry" role="listitem">
Sobri, Sobrina, Sam Koohi-Kamali, and Nasrudin Abd. Rahim. 2018. <span>“Solar Photovoltaic Generation Forecasting Methods: A Review.”</span> <em>Energy Conversion and Management</em> 156: 459–97. https://doi.org/<a href="https://doi.org/10.1016/j.enconman.2017.11.019">https://doi.org/10.1016/j.enconman.2017.11.019</a>.
</div>
<div id="ref-4" class="csl-entry" role="listitem">
Wang, Kejun, Xiaoxia Qi, and Hongda Liu. 2019. <span>“A Comparison of Day-Ahead Photovoltaic Power Forecasting Models Based on Deep Learning Neural Network.”</span> <em>Applied Energy</em> 251: 113315. https://doi.org/<a href="https://doi.org/10.1016/j.apenergy.2019.113315">https://doi.org/10.1016/j.apenergy.2019.113315</a>.
</div>
<div id="ref-1" class="csl-entry" role="listitem">
Zhang, Jinxia, Yuanying Chi, and Linpeng Xiao. 2018. <span>“Solar Power Generation Forecast Based on LSTM.”</span> In <em>2018 IEEE 9th International Conference on Software Engineering and Service Science (ICSESS)</em>, 869–72. <a href="https://doi.org/10.1109/ICSESS.2018.8663788">https://doi.org/10.1109/ICSESS.2018.8663788</a>.
</div>
</div>
<!-- ## Appendix {#sec-appendix} -->


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>