<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sandro Luis R. Silva – dl-here-comes-the-sun---clark-(indiv--silva-s</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/profile.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-9FYFKWYLVG"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-9FYFKWYLVG', { 'anonymize_ip': true});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sandro Luis R. Silva</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html" rel="" target="">
 <span class="menu-text">Resume</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/slrsilva/slrsilva.github.io" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">



<div style="padding:5px">
<font style="font-weight:bold;font-size:32px;color:#2c3393;">Here Comes The Sun: Clark Solar Power Plant</font>
</div>
<div style="padding:5px">
<font style="font-weight:bold;font-size:24px;color:#2c3393;">LT16 - Sandro Silva and Jac Lin Yu</font>
</div>
<div style="padding:5px">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">Individual Project of Sandro Silva</font>
<div>

<hr>
<p><font style="font-weight:bold;font-size:32px;color:#2c3393;">Table of Contents</font></p>
<p><font style="font-size:16px"></font></p><font style="font-size:16px">
<p><strong><a href="#problem-statement">1. Problem Statement</a></strong></p>
<p><strong><a href="#methodology">2. Methodology</a></strong></p>
<ul>
<li><a href="#preq">2.1. Loading Prerequisites</a></li>
<li><a href="#data">2.2. Dataset and Preprocessing</a></li>
<li><a href="#train">2.3. Train, Validation, Test Split and Batch Generation</a></li>
<li><a href="#benchmark">2.4. Determining the Benchmark</a></li>
<li><a href="#model">2.5. Model Training and Selection</a>
<ul>
<li><a href="#lstm1">2.5.1 LSTM with 64 nodes</a></li>
<li><a href="#lstm2">2.5.2 LSTM with 32 nodes</a></li>
<li><a href="#lstm3">2.5.3 Stacked LSTM with 64 and 32 nodes</a></li>
<li><a href="#lstm4">2.5.4 Stacked LSTM with 32 and 64 nodes</a></li>
</ul></li>
</ul>
<p><strong><a href="#results">3. Results and Discussions</a></strong> * <a href="#res">3.1. Results</a> * <a href="#discussions">3.2. Discussions and Recommendations</a></p>
</font><p><font style="font-size:16px"><strong><a href="#summary">4. Summary and Main Learning Points</a></strong> * <a href="#summary">4.1. Summary</a> * <a href="#main">4.1. Main Learning Points</a> </font></p>
<div id="problem-statement">
<div style="padding:3px;">
<font style="font-weight:bold;font-size:20px;color:#2c3393;">1. Problem Statement</font>
</div>
<div style="padding-left: 20px; text-align: justify; font-size:16px; line-height:1.6">
<p>In recent years, the global energy industry has changed its focus away from traditional fuel sources, such as oil and coal, to more alternative and sustainable solutions, such as hydroelectric, solar and wind. However, the shift towards renewable energy poses new threats and challenges to existing power grids across the world. One major concern surrounding renewable energy generation is the inherent variability and intermittency of its fuel source, as this can cause disruptions in power grids. Essentially, renewable energy technologies threaten to overwhelm the grid operators. <br><br> Renewable energy forecasting, in particular solar generation supply, may provide power grid operators the ability to predict and balance energy generation and consumption. In addition, power grid operators will be able to balance and schedule the distribution of generated power for not only renewable power plants but also conventional (and rigid) power plants, such as coal and natural gas.</p>
</div>
<div id="methodology">
<div style="padding:5px;">
<font style="font-weight:bold;font-size:20px;color:#2c3393;">2. Methodology</font>
</div>
<div id="preq">
<div style="padding:5px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.1 Loading Prerequisites</font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-22T10:29:34.456059Z&quot;,&quot;start_time&quot;:&quot;2019-12-22T10:29:34.451884Z&quot;}" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>warnings.simplefilter(action<span class="op">=</span><span class="st">'ignore'</span>, category<span class="op">=</span><span class="pp">FutureWarning</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-22T10:29:37.558609Z&quot;,&quot;start_time&quot;:&quot;2019-12-22T10:29:34.876146Z&quot;}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> MinMaxScaler</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.datasets <span class="im">import</span> imdb</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.preprocessing <span class="im">import</span> sequence</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.models <span class="im">import</span> Sequential</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras <span class="im">import</span> layers</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.optimizers <span class="im">import</span> RMSprop, Adam</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.callbacks <span class="im">import</span> ModelCheckpoint, EarlyStopping</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="data">
<div style="padding:5px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.2 Dataset and Preprocessing</font>
</div>
<div style="padding:5px;">
<p><font style="font-style:italic;font-size:15px;color:#2c3393;"> Here, we will load the already cleaned preprocessed dataset of solar generation per plant per hour. The cleaning was processed outside of this notebook, and followed a framework which follows the industry standard of imputing missing values.</font></p><font style="font-style:italic;font-size:15px;color:#2c3393;">
<b>To list a few processes:</b> - using the average between the before(t-1) and after hour(t+1) - using a 1-week average of all similar intervals (ex, if empty during hour 6 of dec 20, take the moving average of all hour 6 from dec 13-dec19) - using a 4-week moving average of that specific hour and day of the week (ex, if empty during hour 6 of dec 20, we take average of hour 6(dec 13, 6, 29, 22) </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-22T10:30:35.995418Z&quot;,&quot;start_time&quot;:&quot;2019-12-22T10:29:37.561183Z&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_excel(<span class="st">'solar_dataset.xlsx'</span>, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                   sheet_name<span class="op">=</span><span class="st">'clark'</span>, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                   parse_dates<span class="op">=</span>[<span class="st">'DATETIME'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Here let us observe the different datatypes, notice that some columns are objects, some of which will be dropped. </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:14.898307Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:14.881215Z&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>DATETIME         datetime64[ns]
YEAR                      int64
MONTH                     int64
DAY                       int64
HOUR                      int64
RESOURCE_ID              object
MW                      float64
Location                 object
Temperature             float64
Dew Point               float64
Humidity                float64
Wind Speed              float64
Wind Gust                 int64
Pressure                float64
Condition                object
Location_Name            object
dtype: object</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:14.917372Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:14.899802Z&quot;}" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">DATETIME</th>
<th data-quarto-table-cell-role="th">YEAR</th>
<th data-quarto-table-cell-role="th">MONTH</th>
<th data-quarto-table-cell-role="th">DAY</th>
<th data-quarto-table-cell-role="th">HOUR</th>
<th data-quarto-table-cell-role="th">RESOURCE_ID</th>
<th data-quarto-table-cell-role="th">MW</th>
<th data-quarto-table-cell-role="th">Location</th>
<th data-quarto-table-cell-role="th">Temperature</th>
<th data-quarto-table-cell-role="th">Dew Point</th>
<th data-quarto-table-cell-role="th">Humidity</th>
<th data-quarto-table-cell-role="th">Wind Speed</th>
<th data-quarto-table-cell-role="th">Wind Gust</th>
<th data-quarto-table-cell-role="th">Pressure</th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Location_Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2016-12-26 00:00:00</td>
<td>2016</td>
<td>12</td>
<td>26</td>
<td>1</td>
<td>1CLASOL_G01</td>
<td>0.0</td>
<td>RPLC</td>
<td>75.0</td>
<td>70.0</td>
<td>83.0</td>
<td>5.0</td>
<td>0</td>
<td>29.3</td>
<td>Light Rain Shower</td>
<td>ANGELES/PAMPANGA</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2016-12-26 01:00:00</td>
<td>2016</td>
<td>12</td>
<td>26</td>
<td>2</td>
<td>1CLASOL_G01</td>
<td>0.0</td>
<td>RPLC</td>
<td>77.0</td>
<td>68.0</td>
<td>74.0</td>
<td>9.0</td>
<td>0</td>
<td>29.2</td>
<td>Cloudy</td>
<td>ANGELES/PAMPANGA</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2016-12-26 02:00:00</td>
<td>2016</td>
<td>12</td>
<td>26</td>
<td>3</td>
<td>1CLASOL_G01</td>
<td>0.0</td>
<td>RPLC</td>
<td>77.0</td>
<td>70.0</td>
<td>78.0</td>
<td>9.0</td>
<td>0</td>
<td>29.2</td>
<td>Light Rain Shower</td>
<td>ANGELES/PAMPANGA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> It is customary in traditional time-series regression to convert the <code>month</code>, <code>day</code>, <code>hour</code> into categorical data, which will be later used in one-hot encoding. In addition, this is the usual preprocessing used in the energy industry here in the Philippines. </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.045070Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:14.918955Z&quot;}" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df.MONTH <span class="op">=</span> df.MONTH.astype(<span class="st">'str'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>df.DAY <span class="op">=</span> df.DAY.astype(<span class="st">'str'</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df.HOUR <span class="op">=</span> df.HOUR.astype(<span class="st">'str'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Let us drop the unimportant columns </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.075868Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.046202Z&quot;}" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df.drop([<span class="st">'Location_Name'</span>, <span class="st">'Location'</span>, <span class="st">"YEAR"</span>],axis<span class="op">=</span><span class="dv">1</span>,inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Let us append the main <code>df</code> with the one-hot encoded dataframe </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.163769Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.078065Z&quot;}" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.join(pd.get_dummies(df[[<span class="st">'MONTH'</span>,<span class="st">'DAY'</span>,<span class="st">'HOUR'</span>,<span class="st">'Condition'</span>]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Let us get the unique list of power plants in the region </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.173301Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.166471Z&quot;}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>locations <span class="op">=</span> df.RESOURCE_ID.unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> For this study, let us consider the first power plant </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.180358Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.176105Z&quot;}" data-execution_count="10">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>locations[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>'1CLASOL_G01'</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.229579Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.181992Z&quot;}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df0 <span class="op">=</span> df[df.RESOURCE_ID <span class="op">==</span> locations[<span class="dv">0</span>]].copy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Further dropping of columns as well as reordering of columns </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.237316Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.231256Z&quot;}" data-execution_count="12">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df0 <span class="op">=</span> df0.drop([<span class="st">'RESOURCE_ID'</span>,<span class="st">'DATETIME'</span>,<span class="st">'MONTH'</span>,<span class="st">'DAY'</span>,<span class="st">'HOUR'</span>,<span class="st">'Condition'</span>],</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>               axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.245634Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.238992Z&quot;}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df0 <span class="op">=</span> df0[[<span class="st">'Temperature'</span>,<span class="st">'MW'</span>] <span class="op">+</span> df0.columns[<span class="dv">2</span>:].tolist()].copy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.264233Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.247292Z&quot;}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df0 <span class="op">=</span> df0.astype(<span class="st">'float'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Final <code>DataFrame</code> to be used </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.299458Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.266137Z&quot;}" data-execution_count="15">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df0.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Temperature</th>
<th data-quarto-table-cell-role="th">MW</th>
<th data-quarto-table-cell-role="th">Dew Point</th>
<th data-quarto-table-cell-role="th">Humidity</th>
<th data-quarto-table-cell-role="th">Wind Speed</th>
<th data-quarto-table-cell-role="th">Wind Gust</th>
<th data-quarto-table-cell-role="th">Pressure</th>
<th data-quarto-table-cell-role="th">MONTH_1</th>
<th data-quarto-table-cell-role="th">MONTH_10</th>
<th data-quarto-table-cell-role="th">MONTH_11</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Condition_Mostly Cloudy / Windy</th>
<th data-quarto-table-cell-role="th">Condition_Partly Cloudy</th>
<th data-quarto-table-cell-role="th">Condition_Partly Cloudy / Windy</th>
<th data-quarto-table-cell-role="th">Condition_Patches of Fog</th>
<th data-quarto-table-cell-role="th">Condition_Rain</th>
<th data-quarto-table-cell-role="th">Condition_Rain / Windy</th>
<th data-quarto-table-cell-role="th">Condition_Rain Shower</th>
<th data-quarto-table-cell-role="th">Condition_Showers in the Vicinity</th>
<th data-quarto-table-cell-role="th">Condition_T-Storm</th>
<th data-quarto-table-cell-role="th">Condition_Thunder</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>75.0</td>
<td>0.0</td>
<td>70.0</td>
<td>83.0</td>
<td>5.0</td>
<td>0.0</td>
<td>29.3</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>77.0</td>
<td>0.0</td>
<td>68.0</td>
<td>74.0</td>
<td>9.0</td>
<td>0.0</td>
<td>29.2</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>77.0</td>
<td>0.0</td>
<td>70.0</td>
<td>78.0</td>
<td>9.0</td>
<td>0.0</td>
<td>29.2</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>79.0</td>
<td>0.0</td>
<td>70.0</td>
<td>74.0</td>
<td>12.0</td>
<td>0.0</td>
<td>29.2</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>79.0</td>
<td>0.0</td>
<td>70.0</td>
<td>74.0</td>
<td>12.0</td>
<td>0.0</td>
<td>29.2</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>...</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
</tbody>
</table>

<p>5 rows × 101 columns</p>
</div>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.304284Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.300875Z&quot;}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df0.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>(24031, 101)</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.313047Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.305713Z&quot;}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>plant_capacity <span class="op">=</span> <span class="dv">22</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="train">
<div style="padding:5px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;"> 2.3 Train,Validate,Test Split and Batch Generation</font>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> For this analysis, a <code>.8</code>, <code>.1</code>, <code>.1</code>, train-validate-test split was implemented. Since we are dealing with a time-series, the train-validate-test split cannot be randomly selected from the dataset, splitting of dataset should be conducted in a chronogical order. Below we define the starting and ending <code>index</code> for each group </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.318256Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.314840Z&quot;}" data-execution_count="18">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>train_validate_test_split <span class="op">=</span> [<span class="fl">.8</span>, <span class="fl">.1</span>, <span class="fl">.1</span>]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>train_idx <span class="op">=</span> math.floor(df0.shape[<span class="dv">0</span>] <span class="op">*</span> train_validate_test_split[<span class="dv">0</span>])</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>val_idx <span class="op">=</span> math.floor(df0.shape[<span class="dv">0</span>] <span class="op">*</span> train_validate_test_split[<span class="dv">1</span>]) <span class="op">+</span> train_idx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> The <code>generator</code> function below was utilized to yield the appropriate batch. Significant parameters include the <code>lookback</code>, or how far back of the data to consider, <code>delay</code>, or how far into the future are we forecasting, <code>batch_size</code>, refers to the number of training examples utilized in one iteration. </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.328621Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.319786Z&quot;}" data-execution_count="19">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> generator(data, lookback, delay, min_index, max_index, shuffle<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>              batch_size<span class="op">=</span><span class="dv">128</span>, step<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> max_index <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>        max_index <span class="op">=</span> <span class="bu">len</span>(data) <span class="op">-</span> delay <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    i <span class="op">=</span> min_index <span class="op">+</span> lookback</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> <span class="dv">1</span>:</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> shuffle:</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>            rows <span class="op">=</span> np.random.randint(min_index <span class="op">+</span> lookback, </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                                     max_index, size<span class="op">=</span>batch_size)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> i <span class="op">+</span> batch_size <span class="op">&gt;=</span> max_index:</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>                i <span class="op">=</span> min_index <span class="op">+</span> lookback</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>            rows <span class="op">=</span> np.arange(i, <span class="bu">min</span>(i <span class="op">+</span> batch_size, max_index))</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>            i <span class="op">+=</span> <span class="bu">len</span>(rows)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>        samples <span class="op">=</span> np.zeros((<span class="bu">len</span>(rows), lookback <span class="op">//</span> step, data.shape[<span class="op">-</span><span class="dv">1</span>]))</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>        targets <span class="op">=</span> np.zeros((<span class="bu">len</span>(rows),))</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j, row <span class="kw">in</span> <span class="bu">enumerate</span>(rows):</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>            indices <span class="op">=</span> <span class="bu">range</span>(rows[j] <span class="op">-</span> lookback, rows[j], step)</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>            samples[j] <span class="op">=</span> data[indices]</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>            targets[j] <span class="op">=</span> data[rows[j] <span class="op">+</span> delay][<span class="dv">1</span>]</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">yield</span> samples, targets</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Let us mean-center the dataset </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.350053Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.330196Z&quot;}" data-execution_count="20">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>float_data <span class="op">=</span> df0.values</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>train_mean <span class="op">=</span> float_data[:train_idx].mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>float_data <span class="op">-=</span> train_mean</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>train_std <span class="op">=</span> float_data[:train_idx].std(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>float_data <span class="op">/=</span> train_std</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>train_mw_std <span class="op">=</span> train_std[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;">
<font style="font-style:italic;font-size:15px;color:#2c3393;"> Let us initialize the parameters which will be used for the generation An industry standard practic is to utilize a <code>lookback</code> of either <code>144 hours</code> (1 week), <code>288 hours</code> (2 weeks), or <code>720 hours</code> (1[30-day] month). The initial run was to utilized a <code>288 hour</code> lookback period due to group’s industry expert’s experience. However, outside consultation with industry experts said 1 week would suffice with this limited dataset. </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.353772Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.351491Z&quot;}" data-execution_count="21">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>lookback <span class="op">=</span> <span class="dv">144</span> <span class="co"># lookback(consider) the previous week data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>step <span class="op">=</span> <span class="dv">1</span> <span class="co"># in hourly granularity</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>delay <span class="op">=</span> <span class="dv">24</span> <span class="co"># to forecast the next 24 hours</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>batch_size <span class="op">=</span> <span class="dv">128</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:15.360974Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.355309Z&quot;}" data-execution_count="22">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>train_gen <span class="op">=</span> generator(float_data,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    lookback<span class="op">=</span>lookback,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    delay<span class="op">=</span>delay,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    min_index<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    max_index<span class="op">=</span>train_idx,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    step<span class="op">=</span>step,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    batch_size<span class="op">=</span>batch_size)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>val_gen <span class="op">=</span> generator(float_data,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    lookback<span class="op">=</span>lookback,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    delay<span class="op">=</span>delay,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    min_index<span class="op">=</span>train_idx<span class="op">+</span><span class="dv">1</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    max_index<span class="op">=</span>val_idx,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    step<span class="op">=</span>step,</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    batch_size<span class="op">=</span>batch_size)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>test_gen <span class="op">=</span> generator(float_data,</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    lookback<span class="op">=</span>lookback,</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    delay<span class="op">=</span>delay,</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>    min_index<span class="op">=</span>val_idx,</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>    max_index<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>    step<span class="op">=</span>step,</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>    batch_size<span class="op">=</span>batch_size)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>val_steps <span class="op">=</span> (val_idx <span class="op">-</span> (train_idx<span class="op">+</span><span class="dv">1</span>) <span class="op">-</span> lookback)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>test_steps <span class="op">=</span> (<span class="bu">len</span>(float_data) <span class="op">-</span> (val_idx<span class="op">+</span><span class="dv">1</span>) <span class="op">-</span> lookback)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="benchmark">
<div style="padding:5px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.4 Benchmark</font>
</div>
<div style="padding:5px;">
<p><font style="font-style:italic;font-size:15px;color:#2c3393;"> The team used two metrics to establish a baseline error:</font></p><font style="font-style:italic;font-size:15px;color:#2c3393;">
<pre><code>(1) the naive method identified in a previous lecture, which we scaled to industry standard
(2) a different framework suggested by industry</code></pre>
</font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:28.528330Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:15.362379Z&quot;}" data-execution_count="23">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> evaluate_naive_method():</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    batch_maes <span class="op">=</span> []</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(val_steps):</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> step <span class="op">%</span> <span class="dv">1000</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(step)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>        samples, targets <span class="op">=</span> <span class="bu">next</span>(val_gen)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>        preds <span class="op">=</span> samples[:, <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>]</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>        mae <span class="op">=</span> np.mean(np.<span class="bu">abs</span>(preds <span class="op">-</span> targets))</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>        batch_maes.append(mae)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.mean(batch_maes)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>naive_method <span class="op">=</span> evaluate_naive_method()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0
1000
2000</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:28.534496Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:28.531891Z&quot;}" data-execution_count="24">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'NAIVE METHOD 1:'</span>, <span class="ss">f'</span><span class="sc">{</span>((naive_method <span class="op">*</span> train_mw_std)<span class="op">/</span><span class="dv">22</span>)<span class="sc">:0.2%}</span><span class="ss">'</span>) <span class="co">#where 22 is the capacity of the plant</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NAIVE METHOD 1: 6.58%</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:28.586762Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:28.535943Z&quot;}" data-execution_count="25">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>benchmark1 <span class="op">=</span> ((naive_method <span class="op">*</span> train_mw_std)<span class="op">/</span><span class="dv">22</span>) <span class="op">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="padding:5px;text-align:justify">
<p><font style="font-style:italic;font-size:17px;color:#2c3393;"> For establishing the 2nd baseline error, the team consulted the industry to determine a baseline error. However, even the industry is still conflicted on how to establish a baseline measurement. As of now, the baseline is still being established by policy makers and grid operators. <br></font></p><font style="font-style:italic;font-size:17px;color:#2c3393;">
<p>Luckily, consulting with industry experts gave the team a framework on how to establish a baseline error per plant. The resulting measure looked at the mean squared error of the day-ahead projection(DAP), also called scheduled (Ex-Ante or RTD), and the actual delivered (Ex-Post or RTX).</p>
This was then scaled as a percentage to the capacity of the plant. This was with processed with an industry expert and not included in the notebook. The yielding error resulted with a baseline of <code>12.01%</code> </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:28.599905Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:28.593186Z&quot;}" data-execution_count="26">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>benchmark2 <span class="op">=</span> <span class="fl">12.01</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="model">
<div style="padding:5px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.5 Model Training Selection</font>
</div>
<div style="padding:5px;">
<p><font style="font-style:italic;font-size:15px;color:#2c3393;"> The team utilized 4 models:</font></p><font style="font-style:italic;font-size:15px;color:#2c3393;">
<pre><code>- LSTM with 64 nodes
- LSTM with 32 nodes
- Stacked LSTM(2 layer) with 64 and 32 nodes
- Stacked LSTM(2 layer) with 32 and 64 nodes</code></pre>
<p>Dropout of <code>0.2</code> and Recurrent Dropout of <code>0.2</code> and a <code>RMSProp</code> optimized was implemented for all three.</p>
The group decided to use a <code>Epoch=50</code>, with an EarlyStopping of <code>patience=10</code> and <code>min_delta=0.01</code> to avoid overfitting and to reduce runtime due to the limited time constraints. Lastly, the ModelCheckpoint was utilized to extract the best model. </font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T17:58:28.610670Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:28.604405Z&quot;}" data-execution_count="27">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>steps_per_epoch_cnt <span class="op">=</span> math.floor(train_idx<span class="op">/</span>batch_size)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>val_steps_cnt <span class="op">=</span> <span class="bu">round</span>(math.floor((val_idx<span class="op">-</span>train_idx)<span class="op">/</span>batch_size),<span class="op">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="lstm1">
<div style="padding:20px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.5.1 LSTM with 64</font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:05:51.266426Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T17:58:28.613478Z&quot;}" data-execution_count="28">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>filepath_lstm64<span class="op">=</span><span class="st">"clark_best_lstm64.hdf5"</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>cp_lstm64 <span class="op">=</span> ModelCheckpoint(filepath_lstm64, monitor<span class="op">=</span><span class="st">'val_loss'</span>, verbose<span class="op">=</span><span class="dv">2</span>, save_best_only<span class="op">=</span><span class="va">True</span>, mode<span class="op">=</span><span class="st">'min'</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>es_lstm64 <span class="op">=</span> EarlyStopping(monitor<span class="op">=</span><span class="st">'val_loss'</span>, mode<span class="op">=</span><span class="st">'min'</span>, verbose<span class="op">=</span><span class="dv">2</span>, patience<span class="op">=</span><span class="dv">10</span>, min_delta<span class="op">=</span><span class="fl">.01</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>callbacks_list_lstm64 <span class="op">=</span> [cp_lstm64, es_lstm64]</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fix random seed for reproducibility</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>seed <span class="op">=</span> <span class="dv">1337</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(seed)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>model_lstm64 <span class="op">=</span> Sequential()</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>model_lstm64.add(layers.LSTM(<span class="dv">64</span>, </span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>                       dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>                       recurrent_dropout<span class="op">=</span><span class="fl">0.2</span>, </span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>                       input_shape<span class="op">=</span>(<span class="va">None</span>, float_data.shape[<span class="op">-</span><span class="dv">1</span>])))</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>model_lstm64.add(layers.Dense(<span class="dv">64</span>,activation<span class="op">=</span><span class="st">'relu'</span>))</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>model_lstm64.add(layers.Dense(<span class="dv">1</span>))</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>model_lstm64.<span class="bu">compile</span>(optimizer<span class="op">=</span>RMSprop(), loss<span class="op">=</span><span class="st">'mae'</span>)</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>history_lstm64 <span class="op">=</span> model_lstm64.fit_generator(train_gen,</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>                                        steps_per_epoch<span class="op">=</span>steps_per_epoch_cnt, </span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>                                        epochs<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>                                        validation_data<span class="op">=</span>val_gen, </span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>                                        validation_steps<span class="op">=</span>val_steps_cnt,</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>                                        callbacks<span class="op">=</span>callbacks_list_lstm64, verbose<span class="op">=</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>WARNING:tensorflow:From /home/ssilva/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/ssilva/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/ssilva/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
20/20 [==============================] - 1s 47ms/step - loss: 0.1993

Epoch 00001: val_loss improved from inf to 0.19933, saving model to clark_best_lstm64.hdf5
 - 19s - loss: 0.4025 - val_loss: 0.1993
Epoch 2/50
20/20 [==============================] - 1s 43ms/step - loss: 0.1724

Epoch 00002: val_loss improved from 0.19933 to 0.17236, saving model to clark_best_lstm64.hdf5
 - 19s - loss: 0.2765 - val_loss: 0.1724
Epoch 3/50
20/20 [==============================] - 1s 43ms/step - loss: 0.1564

Epoch 00003: val_loss improved from 0.17236 to 0.15639, saving model to clark_best_lstm64.hdf5
 - 19s - loss: 0.2005 - val_loss: 0.1564
Epoch 4/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1634

Epoch 00004: val_loss did not improve from 0.15639
 - 19s - loss: 0.1664 - val_loss: 0.1634
Epoch 5/50
20/20 [==============================] - 1s 43ms/step - loss: 0.1585

Epoch 00005: val_loss did not improve from 0.15639
 - 19s - loss: 0.1598 - val_loss: 0.1585
Epoch 6/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1697

Epoch 00006: val_loss did not improve from 0.15639
 - 19s - loss: 0.1500 - val_loss: 0.1697
Epoch 7/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1465

Epoch 00007: val_loss improved from 0.15639 to 0.14650, saving model to clark_best_lstm64.hdf5
 - 19s - loss: 0.1445 - val_loss: 0.1465
Epoch 8/50
20/20 [==============================] - 1s 43ms/step - loss: 0.1521

Epoch 00008: val_loss did not improve from 0.14650
 - 19s - loss: 0.1431 - val_loss: 0.1521
Epoch 9/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1565

Epoch 00009: val_loss did not improve from 0.14650
 - 19s - loss: 0.1339 - val_loss: 0.1565
Epoch 10/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1584

Epoch 00010: val_loss did not improve from 0.14650
 - 19s - loss: 0.1301 - val_loss: 0.1584
Epoch 11/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1515

Epoch 00011: val_loss did not improve from 0.14650
 - 19s - loss: 0.1297 - val_loss: 0.1515
Epoch 12/50
20/20 [==============================] - 1s 43ms/step - loss: 0.1624

Epoch 00012: val_loss did not improve from 0.14650
 - 19s - loss: 0.1285 - val_loss: 0.1624
Epoch 13/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1430

Epoch 00013: val_loss improved from 0.14650 to 0.14299, saving model to clark_best_lstm64.hdf5
 - 21s - loss: 0.1255 - val_loss: 0.1430
Epoch 14/50
20/20 [==============================] - 1s 53ms/step - loss: 0.1586

Epoch 00014: val_loss did not improve from 0.14299
 - 23s - loss: 0.1221 - val_loss: 0.1586
Epoch 15/50
20/20 [==============================] - 1s 38ms/step - loss: 0.1457

Epoch 00015: val_loss did not improve from 0.14299
 - 19s - loss: 0.1162 - val_loss: 0.1457
Epoch 16/50
20/20 [==============================] - 1s 38ms/step - loss: 0.1452

Epoch 00016: val_loss did not improve from 0.14299
 - 18s - loss: 0.1186 - val_loss: 0.1452
Epoch 17/50
20/20 [==============================] - 1s 39ms/step - loss: 0.1591

Epoch 00017: val_loss did not improve from 0.14299
 - 19s - loss: 0.1152 - val_loss: 0.1591
Epoch 18/50
20/20 [==============================] - 1s 38ms/step - loss: 0.1563

Epoch 00018: val_loss did not improve from 0.14299
 - 19s - loss: 0.1138 - val_loss: 0.1563
Epoch 19/50
20/20 [==============================] - 1s 38ms/step - loss: 0.1538

Epoch 00019: val_loss did not improve from 0.14299
 - 18s - loss: 0.1129 - val_loss: 0.1538
Epoch 20/50
20/20 [==============================] - 1s 38ms/step - loss: 0.1551

Epoch 00020: val_loss did not improve from 0.14299
 - 18s - loss: 0.1128 - val_loss: 0.1551
Epoch 21/50
20/20 [==============================] - 1s 38ms/step - loss: 0.1505

Epoch 00021: val_loss did not improve from 0.14299
 - 19s - loss: 0.1118 - val_loss: 0.1505
Epoch 22/50
20/20 [==============================] - 1s 42ms/step - loss: 0.1461

Epoch 00022: val_loss did not improve from 0.14299
 - 19s - loss: 0.1109 - val_loss: 0.1461
Epoch 23/50
20/20 [==============================] - 1s 41ms/step - loss: 0.1543

Epoch 00023: val_loss did not improve from 0.14299
 - 23s - loss: 0.1093 - val_loss: 0.1543
Epoch 00023: early stopping</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:05:51.474772Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:05:51.268311Z&quot;}" data-execution_count="29">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>loss_lstm64 <span class="op">=</span> history_lstm64.history[<span class="st">'loss'</span>]</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>val_loss_lstm64 <span class="op">=</span> history_lstm64.history[<span class="st">'val_loss'</span>]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>epochs <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(loss_lstm64) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, loss_lstm64, <span class="st">'bo'</span>, label<span class="op">=</span><span class="st">'Training loss'</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, val_loss_lstm64, <span class="st">'b'</span>, label<span class="op">=</span><span class="st">'Validation loss'</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Training and validation loss'</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="[DL] Here Comes the Sun - CLARK (Indiv- Silva, S)_files/figure-html/cell-30-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:05:51.480302Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:05:51.476311Z&quot;}" data-execution_count="30">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Model Error:'</span>, <span class="ss">f'</span><span class="sc">{</span>((<span class="bu">min</span>(val_loss_lstm64) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity)<span class="sc">:0.2%}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Error: 3.21%</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:32:54.937967Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:32:54.932441Z&quot;}" data-execution_count="52">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lstm64 <span class="op">=</span> ((<span class="bu">min</span>(val_loss_lstm64) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity) <span class="op">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="lstm2">
<div style="padding:20px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.5.2 LSTM with 32 nodes</font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:09:35.066495Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:05:51.485199Z&quot;}" data-execution_count="32">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>filepath_lstm32<span class="op">=</span><span class="st">"clark_best_lstm32.hdf5"</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>cp_lstm32 <span class="op">=</span> ModelCheckpoint(filepath_lstm32, monitor<span class="op">=</span><span class="st">'val_loss'</span>, verbose<span class="op">=</span><span class="dv">2</span>, save_best_only<span class="op">=</span><span class="va">True</span>, mode<span class="op">=</span><span class="st">'min'</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>es_lstm32 <span class="op">=</span> EarlyStopping(monitor<span class="op">=</span><span class="st">'val_loss'</span>, mode<span class="op">=</span><span class="st">'min'</span>, verbose<span class="op">=</span><span class="dv">2</span>, patience<span class="op">=</span><span class="dv">10</span>, min_delta<span class="op">=</span><span class="fl">.01</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>callbacks_list_lstm32 <span class="op">=</span> [cp_lstm32, es_lstm32]</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fix random seed for reproducibility</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>seed <span class="op">=</span> <span class="dv">1337</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(seed)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>model_lstm32 <span class="op">=</span> Sequential()</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>model_lstm32.add(layers.LSTM(<span class="dv">32</span>, </span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>                       dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>                       recurrent_dropout<span class="op">=</span><span class="fl">0.2</span>, </span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>                       input_shape<span class="op">=</span>(<span class="va">None</span>, float_data.shape[<span class="op">-</span><span class="dv">1</span>])))</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>model_lstm32.add(layers.Dense(<span class="dv">32</span>, activation<span class="op">=</span><span class="st">'relu'</span>))</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>model_lstm32.add(layers.Dense(<span class="dv">1</span>))</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>model_lstm32.<span class="bu">compile</span>(optimizer<span class="op">=</span>RMSprop(), loss<span class="op">=</span><span class="st">'mae'</span>)</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>history_lstm32 <span class="op">=</span> model_lstm32.fit_generator(train_gen,</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>                                        steps_per_epoch<span class="op">=</span>steps_per_epoch_cnt, </span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>                                        epochs<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>                                        validation_data<span class="op">=</span>val_gen, </span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>                                        validation_steps<span class="op">=</span>val_steps_cnt,</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>                                        callbacks<span class="op">=</span>callbacks_list_lstm32, verbose<span class="op">=</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/50
20/20 [==============================] - 1s 41ms/step - loss: 0.1916

Epoch 00001: val_loss improved from inf to 0.19160, saving model to clark_best_lstm32.hdf5
 - 17s - loss: 0.4936 - val_loss: 0.1916
Epoch 2/50
20/20 [==============================] - 1s 34ms/step - loss: 0.1696

Epoch 00002: val_loss improved from 0.19160 to 0.16960, saving model to clark_best_lstm32.hdf5
 - 19s - loss: 0.3050 - val_loss: 0.1696
Epoch 3/50
20/20 [==============================] - 1s 31ms/step - loss: 0.1460

Epoch 00003: val_loss improved from 0.16960 to 0.14600, saving model to clark_best_lstm32.hdf5
 - 17s - loss: 0.2672 - val_loss: 0.1460
Epoch 4/50
20/20 [==============================] - 1s 31ms/step - loss: 0.1610

Epoch 00004: val_loss did not improve from 0.14600
 - 17s - loss: 0.2259 - val_loss: 0.1610
Epoch 5/50
20/20 [==============================] - 1s 35ms/step - loss: 0.1525

Epoch 00005: val_loss did not improve from 0.14600
 - 17s - loss: 0.2027 - val_loss: 0.1525
Epoch 6/50
20/20 [==============================] - 1s 36ms/step - loss: 0.1681

Epoch 00006: val_loss did not improve from 0.14600
 - 16s - loss: 0.1687 - val_loss: 0.1681
Epoch 7/50
20/20 [==============================] - 1s 30ms/step - loss: 0.1471

Epoch 00007: val_loss did not improve from 0.14600
 - 17s - loss: 0.1564 - val_loss: 0.1471
Epoch 8/50
20/20 [==============================] - 1s 31ms/step - loss: 0.1418

Epoch 00008: val_loss improved from 0.14600 to 0.14184, saving model to clark_best_lstm32.hdf5
 - 16s - loss: 0.1522 - val_loss: 0.1418
Epoch 9/50
20/20 [==============================] - 1s 31ms/step - loss: 0.1502

Epoch 00009: val_loss did not improve from 0.14184
 - 17s - loss: 0.1418 - val_loss: 0.1502
Epoch 10/50
20/20 [==============================] - 1s 38ms/step - loss: 0.1595

Epoch 00010: val_loss did not improve from 0.14184
 - 19s - loss: 0.1390 - val_loss: 0.1595
Epoch 11/50
20/20 [==============================] - 1s 30ms/step - loss: 0.1491

Epoch 00011: val_loss did not improve from 0.14184
 - 17s - loss: 0.1370 - val_loss: 0.1491
Epoch 12/50
20/20 [==============================] - 1s 34ms/step - loss: 0.1505

Epoch 00012: val_loss did not improve from 0.14184
 - 17s - loss: 0.1363 - val_loss: 0.1505
Epoch 13/50
20/20 [==============================] - 1s 33ms/step - loss: 0.1394

Epoch 00013: val_loss improved from 0.14184 to 0.13940, saving model to clark_best_lstm32.hdf5
 - 17s - loss: 0.1334 - val_loss: 0.1394
Epoch 00013: early stopping</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:09:35.322694Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:09:35.069357Z&quot;}" data-execution_count="33">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>loss_lstm32 <span class="op">=</span> history_lstm32.history[<span class="st">'loss'</span>]</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>val_loss_lstm32 <span class="op">=</span> history_lstm32.history[<span class="st">'val_loss'</span>]</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>epochs <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(loss_lstm32) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, loss_lstm32, <span class="st">'bo'</span>, label<span class="op">=</span><span class="st">'Training loss'</span>)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, val_loss_lstm32, <span class="st">'b'</span>, label<span class="op">=</span><span class="st">'Validation loss'</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Training and validation loss'</span>)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="[DL] Here Comes the Sun - CLARK (Indiv- Silva, S)_files/figure-html/cell-34-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:09:35.328254Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:09:35.324358Z&quot;}" data-execution_count="34">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Model Error:'</span>, <span class="ss">f'</span><span class="sc">{</span>((<span class="bu">min</span>(val_loss_lstm32) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity)<span class="sc">:0.2%}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Error: 3.13%</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:32:47.332565Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:32:47.327600Z&quot;}" data-execution_count="51">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>lstm32 <span class="op">=</span> ((<span class="bu">min</span>(val_loss_lstm32) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity) <span class="op">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="lstm3">
<div style="padding:20px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.5.3 Stacked LSTM with 64 and 32 nodes</font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:18:29.242322Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:11:22.635082Z&quot;}" data-execution_count="38">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>filepath_lstm6432<span class="op">=</span><span class="st">"clark_best_lstm6432.hdf5"</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>cp_lstm6432 <span class="op">=</span> ModelCheckpoint(filepath_lstm6432, monitor<span class="op">=</span><span class="st">'val_loss'</span>, verbose<span class="op">=</span><span class="dv">2</span>, save_best_only<span class="op">=</span><span class="va">True</span>, mode<span class="op">=</span><span class="st">'min'</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>es_lstm6432 <span class="op">=</span> EarlyStopping(monitor<span class="op">=</span><span class="st">'val_loss'</span>, mode<span class="op">=</span><span class="st">'min'</span>, verbose<span class="op">=</span><span class="dv">2</span>, patience<span class="op">=</span><span class="dv">10</span>, min_delta<span class="op">=</span><span class="fl">.01</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>callbacks_list_lstm6432 <span class="op">=</span> [cp_lstm6432, es_lstm6432]</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fix random seed for reproducibility</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>seed <span class="op">=</span> <span class="dv">1337</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(seed)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>model_lstm6432 <span class="op">=</span> Sequential()</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>model_lstm6432.add(layers.LSTM(<span class="dv">64</span>,</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>                    dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>                    recurrent_dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>                    return_sequences<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>                    input_shape<span class="op">=</span>(<span class="va">None</span>, float_data.shape[<span class="op">-</span><span class="dv">1</span>])))</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>model_lstm6432.add(layers.LSTM(<span class="dv">32</span>,</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>                    dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>                    recurrent_dropout<span class="op">=</span><span class="fl">0.2</span>))</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>model_lstm6432.add(layers.Dense(<span class="dv">32</span>, activation<span class="op">=</span><span class="st">'relu'</span>))</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>model_lstm6432.add(layers.Dense(<span class="dv">1</span>))</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>model_lstm6432.<span class="bu">compile</span>(optimizer<span class="op">=</span>RMSprop(), loss<span class="op">=</span><span class="st">'mae'</span>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>history_lstm6432 <span class="op">=</span> model_lstm6432.fit_generator(train_gen,</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>                                             steps_per_epoch<span class="op">=</span>steps_per_epoch_cnt,</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>                                             epochs<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>                                             validation_data<span class="op">=</span>val_gen, </span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>                                             validation_steps<span class="op">=</span>val_steps_cnt,</span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>                                             callbacks<span class="op">=</span>callbacks_list_lstm6432, verbose<span class="op">=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/50
20/20 [==============================] - 2s 77ms/step - loss: 0.1807

Epoch 00001: val_loss improved from inf to 0.18073, saving model to clark_best_lstm6432.hdf5
 - 35s - loss: 0.4037 - val_loss: 0.1807
Epoch 2/50
20/20 [==============================] - 2s 80ms/step - loss: 0.1452

Epoch 00002: val_loss improved from 0.18073 to 0.14524, saving model to clark_best_lstm6432.hdf5
 - 34s - loss: 0.2290 - val_loss: 0.1452
Epoch 3/50
20/20 [==============================] - 1s 60ms/step - loss: 0.1595

Epoch 00003: val_loss did not improve from 0.14524
 - 41s - loss: 0.1754 - val_loss: 0.1595
Epoch 4/50
20/20 [==============================] - 1s 60ms/step - loss: 0.1460

Epoch 00004: val_loss did not improve from 0.14524
 - 34s - loss: 0.1528 - val_loss: 0.1460
Epoch 5/50
20/20 [==============================] - 1s 70ms/step - loss: 0.1535

Epoch 00005: val_loss did not improve from 0.14524
 - 37s - loss: 0.1483 - val_loss: 0.1535
Epoch 6/50
20/20 [==============================] - 1s 67ms/step - loss: 0.1510

Epoch 00006: val_loss did not improve from 0.14524
 - 39s - loss: 0.1385 - val_loss: 0.1510
Epoch 7/50
20/20 [==============================] - 1s 66ms/step - loss: 0.1482

Epoch 00007: val_loss did not improve from 0.14524
 - 35s - loss: 0.1345 - val_loss: 0.1482
Epoch 8/50
20/20 [==============================] - 1s 66ms/step - loss: 0.1382

Epoch 00008: val_loss improved from 0.14524 to 0.13823, saving model to clark_best_lstm6432.hdf5
 - 34s - loss: 0.1336 - val_loss: 0.1382
Epoch 9/50
20/20 [==============================] - 1s 66ms/step - loss: 0.1606

Epoch 00009: val_loss did not improve from 0.13823
 - 34s - loss: 0.1249 - val_loss: 0.1606
Epoch 10/50
20/20 [==============================] - 1s 68ms/step - loss: 0.1529

Epoch 00010: val_loss did not improve from 0.13823
 - 34s - loss: 0.1214 - val_loss: 0.1529
Epoch 11/50
20/20 [==============================] - 1s 66ms/step - loss: 0.1430

Epoch 00011: val_loss did not improve from 0.13823
 - 34s - loss: 0.1213 - val_loss: 0.1430
Epoch 12/50
20/20 [==============================] - 1s 66ms/step - loss: 0.1400

Epoch 00012: val_loss did not improve from 0.13823
 - 34s - loss: 0.1209 - val_loss: 0.1400
Epoch 00012: early stopping</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:18:29.463963Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:18:29.244219Z&quot;}" data-execution_count="39">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>loss_lstm6432 <span class="op">=</span> history_lstm6432.history[<span class="st">'loss'</span>]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>val_loss_lstm6432 <span class="op">=</span> history_lstm6432.history[<span class="st">'val_loss'</span>]</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>epochs <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(loss_lstm6432) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, loss_lstm6432, <span class="st">'bo'</span>, label<span class="op">=</span><span class="st">'Training loss'</span>)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, val_loss_lstm6432, <span class="st">'b'</span>, label<span class="op">=</span><span class="st">'Validation loss'</span>)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Training and validation loss'</span>)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="[DL] Here Comes the Sun - CLARK (Indiv- Silva, S)_files/figure-html/cell-38-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:18:29.469226Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:18:29.466177Z&quot;}" data-execution_count="40">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Model Error:'</span>, <span class="ss">f'</span><span class="sc">{</span>((<span class="bu">min</span>(val_loss_lstm6432) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity)<span class="sc">:0.2%}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Error: 3.10%</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:32:30.843071Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:32:30.839403Z&quot;}" data-execution_count="49">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>lstm6432 <span class="op">=</span> ((<span class="bu">min</span>(val_loss_lstm6432) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity) <span class="op">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="lstm4">
<div style="padding:20px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">2.5.4 Stacked LSTM with 32 and 64 nodes</font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:32:02.310018Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:18:29.475148Z&quot;}" data-execution_count="42">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>filepath_lstm3264 <span class="op">=</span><span class="st">"clark_best_lstm3264.hdf5"</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>cp_lstm3264 <span class="op">=</span> ModelCheckpoint(filepath_lstm3264, monitor<span class="op">=</span><span class="st">'val_loss'</span>, verbose<span class="op">=</span><span class="dv">2</span>, save_best_only<span class="op">=</span><span class="va">True</span>, mode<span class="op">=</span><span class="st">'min'</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>es_lstm3264 <span class="op">=</span> EarlyStopping(monitor<span class="op">=</span><span class="st">'val_loss'</span>, mode<span class="op">=</span><span class="st">'min'</span>, verbose<span class="op">=</span><span class="dv">2</span>, patience<span class="op">=</span><span class="dv">10</span>, min_delta<span class="op">=</span><span class="fl">.01</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>callbacks_list_lstm3264 <span class="op">=</span> [cp_lstm3264, es_lstm3264]</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fix random seed for reproducibility</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>seed <span class="op">=</span> <span class="dv">1337</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(seed)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>model_lstm3264 <span class="op">=</span> Sequential()</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>model_lstm3264.add(layers.LSTM(<span class="dv">64</span>,</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>                    dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>                    recurrent_dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>                    return_sequences<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>                    input_shape<span class="op">=</span>(<span class="va">None</span>, float_data.shape[<span class="op">-</span><span class="dv">1</span>])))</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>model_lstm3264.add(layers.LSTM(<span class="dv">32</span>,</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>                    dropout<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>                    recurrent_dropout<span class="op">=</span><span class="fl">0.2</span>))</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>model_lstm3264.add(layers.Dense(<span class="dv">64</span>, activation<span class="op">=</span><span class="st">'relu'</span>))</span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>model_lstm3264.add(layers.Dense(<span class="dv">1</span>))</span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>model_lstm3264.<span class="bu">compile</span>(optimizer<span class="op">=</span>RMSprop(), loss<span class="op">=</span><span class="st">'mae'</span>)</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>history_lstm3264 <span class="op">=</span> model_lstm3264.fit_generator(train_gen,</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>                                             steps_per_epoch<span class="op">=</span>steps_per_epoch_cnt,</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>                                             epochs<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>                                             validation_data<span class="op">=</span>val_gen, </span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>                                             validation_steps<span class="op">=</span>val_steps_cnt,</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>                                             callbacks<span class="op">=</span>callbacks_list_lstm3264, verbose<span class="op">=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/50
20/20 [==============================] - 2s 77ms/step - loss: 0.1807

Epoch 00001: val_loss improved from inf to 0.18071, saving model to clark_best_lstm3264.hdf5
 - 36s - loss: 0.4016 - val_loss: 0.1807
Epoch 2/50
20/20 [==============================] - 1s 65ms/step - loss: 0.1537

Epoch 00002: val_loss improved from 0.18071 to 0.15374, saving model to clark_best_lstm3264.hdf5
 - 33s - loss: 0.2138 - val_loss: 0.1537
Epoch 3/50
20/20 [==============================] - 1s 65ms/step - loss: 0.1639

Epoch 00003: val_loss did not improve from 0.15374
 - 33s - loss: 0.1709 - val_loss: 0.1639
Epoch 4/50
20/20 [==============================] - 1s 64ms/step - loss: 0.1513

Epoch 00004: val_loss improved from 0.15374 to 0.15125, saving model to clark_best_lstm3264.hdf5
 - 33s - loss: 0.1528 - val_loss: 0.1513
Epoch 5/50
20/20 [==============================] - 1s 66ms/step - loss: 0.1401

Epoch 00005: val_loss improved from 0.15125 to 0.14008, saving model to clark_best_lstm3264.hdf5
 - 33s - loss: 0.1501 - val_loss: 0.1401
Epoch 6/50
20/20 [==============================] - 1s 65ms/step - loss: 0.1481

Epoch 00006: val_loss did not improve from 0.14008
 - 33s - loss: 0.1413 - val_loss: 0.1481
Epoch 7/50
20/20 [==============================] - 1s 65ms/step - loss: 0.1498

Epoch 00007: val_loss did not improve from 0.14008
 - 33s - loss: 0.1372 - val_loss: 0.1498
Epoch 8/50
20/20 [==============================] - 1s 65ms/step - loss: 0.1588

Epoch 00008: val_loss did not improve from 0.14008
 - 33s - loss: 0.1362 - val_loss: 0.1588
Epoch 9/50
20/20 [==============================] - 1s 71ms/step - loss: 0.1470

Epoch 00009: val_loss did not improve from 0.14008
 - 33s - loss: 0.1273 - val_loss: 0.1470
Epoch 10/50
20/20 [==============================] - 1s 64ms/step - loss: 0.1598

Epoch 00010: val_loss did not improve from 0.14008
 - 36s - loss: 0.1242 - val_loss: 0.1598
Epoch 11/50
20/20 [==============================] - 1s 59ms/step - loss: 0.1428

Epoch 00011: val_loss did not improve from 0.14008
 - 34s - loss: 0.1246 - val_loss: 0.1428
Epoch 12/50
20/20 [==============================] - 1s 59ms/step - loss: 0.1389

Epoch 00012: val_loss improved from 0.14008 to 0.13890, saving model to clark_best_lstm3264.hdf5
 - 33s - loss: 0.1239 - val_loss: 0.1389
Epoch 13/50
20/20 [==============================] - 1s 66ms/step - loss: 0.1276

Epoch 00013: val_loss improved from 0.13890 to 0.12760, saving model to clark_best_lstm3264.hdf5
 - 39s - loss: 0.1203 - val_loss: 0.1276
Epoch 14/50
20/20 [==============================] - 1s 68ms/step - loss: 0.1609

Epoch 00014: val_loss did not improve from 0.12760
 - 37s - loss: 0.1178 - val_loss: 0.1609
Epoch 15/50
20/20 [==============================] - 1s 70ms/step - loss: 0.1446

Epoch 00015: val_loss did not improve from 0.12760
 - 36s - loss: 0.1108 - val_loss: 0.1446
Epoch 16/50
20/20 [==============================] - 1s 69ms/step - loss: 0.1417

Epoch 00016: val_loss did not improve from 0.12760
 - 36s - loss: 0.1140 - val_loss: 0.1417
Epoch 17/50
20/20 [==============================] - 1s 67ms/step - loss: 0.1453

Epoch 00017: val_loss did not improve from 0.12760
 - 37s - loss: 0.1111 - val_loss: 0.1453
Epoch 18/50
20/20 [==============================] - 1s 72ms/step - loss: 0.1500

Epoch 00018: val_loss did not improve from 0.12760
 - 38s - loss: 0.1105 - val_loss: 0.1500
Epoch 19/50
20/20 [==============================] - 1s 68ms/step - loss: 0.1578

Epoch 00019: val_loss did not improve from 0.12760
 - 36s - loss: 0.1090 - val_loss: 0.1578
Epoch 20/50
20/20 [==============================] - 1s 65ms/step - loss: 0.1500

Epoch 00020: val_loss did not improve from 0.12760
 - 37s - loss: 0.1094 - val_loss: 0.1500
Epoch 21/50
20/20 [==============================] - 1s 69ms/step - loss: 0.1490

Epoch 00021: val_loss did not improve from 0.12760
 - 36s - loss: 0.1088 - val_loss: 0.1490
Epoch 22/50
20/20 [==============================] - 1s 67ms/step - loss: 0.1482

Epoch 00022: val_loss did not improve from 0.12760
 - 36s - loss: 0.1063 - val_loss: 0.1482
Epoch 23/50
20/20 [==============================] - 1s 69ms/step - loss: 0.1551

Epoch 00023: val_loss did not improve from 0.12760
 - 36s - loss: 0.1036 - val_loss: 0.1551
Epoch 00023: early stopping</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:32:02.524020Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:32:02.311929Z&quot;}" data-execution_count="43">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>loss_lstm3264 <span class="op">=</span> history_lstm3264.history[<span class="st">'loss'</span>]</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>val_loss_lstm3264 <span class="op">=</span> history_lstm3264.history[<span class="st">'val_loss'</span>]</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>epochs <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(loss_lstm3264) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, loss_lstm3264, <span class="st">'bo'</span>, label<span class="op">=</span><span class="st">'Training loss'</span>)</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>plt.plot(epochs, val_loss_lstm3264, <span class="st">'b'</span>, label<span class="op">=</span><span class="st">'Validation loss'</span>)</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Training and validation loss'</span>)</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="[DL] Here Comes the Sun - CLARK (Indiv- Silva, S)_files/figure-html/cell-42-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:32:02.530032Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:32:02.526018Z&quot;}" data-execution_count="44">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Model Error:'</span>, <span class="ss">f'</span><span class="sc">{</span>((<span class="bu">min</span>(val_loss_lstm3264) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity)<span class="sc">:0.2%}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Error: 2.86%</code></pre>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:32:35.926288Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:32:35.923528Z&quot;}" data-execution_count="50">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>lstm3264 <span class="op">=</span> ((<span class="bu">min</span>(val_loss_lstm3264) <span class="op">*</span> train_mw_std)<span class="op">/</span>plant_capacity) <span class="op">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="results">
<div style="padding:3px;">
<font style="font-weight:bold;font-size:20px;color:#2c3393;">3. Results and Discussions</font>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:33:03.117143Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:33:03.113889Z&quot;}" data-execution_count="53">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> [<span class="st">'Industry Agnostic Naive Method'</span>,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>         <span class="st">'Industry Standard Naive Method'</span>, </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">'LSTM with 64 nodes'</span>,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>         <span class="st">'LSTM with 32 nodes'</span>,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>         <span class="st">'LSTM+LSTM with 64 nodes and 32 nodes'</span>,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>         <span class="st">'LSTM+LSTM with 32 nodes and 64 nodes'</span>]</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> [benchmark1, </span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>           benchmark2,</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>           lstm64,</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>           lstm32,</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>           lstm6432,</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>           lstm3264]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T18:33:03.541129Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T18:33:03.536603Z&quot;}" data-execution_count="54">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> pd.DataFrame(<span class="bu">zip</span>(names,results), columns<span class="op">=</span>[<span class="st">'Model'</span>, <span class="st">'Error in Percentage'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T19:21:41.440637Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T19:21:41.436318Z&quot;}" data-execution_count="57">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>results[<span class="st">'Error in Percentage'</span>] <span class="op">=</span> <span class="bu">round</span>(results[<span class="st">'Error in Percentage'</span>],<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T19:26:59.817743Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T19:26:59.811066Z&quot;}" data-execution_count="71">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>results[<span class="st">'Improvement'</span>] <span class="op">=</span> <span class="bu">round</span>(<span class="dv">1</span><span class="op">-</span>(results[<span class="st">'Error in Percentage'</span>]<span class="op">/</span><span class="fl">12.01</span>),<span class="dv">4</span>)<span class="op">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2019-12-20T19:27:01.126010Z&quot;,&quot;start_time&quot;:&quot;2019-12-20T19:27:01.116017Z&quot;}" data-execution_count="72">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="72">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Error in Percentage</th>
<th data-quarto-table-cell-role="th">Improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Industry Agnostic Naive Method</td>
<td>6.58</td>
<td>45.21</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Industry Standard Naive Method</td>
<td>12.01</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>LSTM with 64 nodes</td>
<td>3.21</td>
<td>73.27</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>LSTM with 32 nodes</td>
<td>3.13</td>
<td>73.94</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>LSTM+LSTM with 64 nodes and 32 nodes</td>
<td>3.10</td>
<td>74.19</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>LSTM+LSTM with 32 nodes and 64 nodes</td>
<td>2.86</td>
<td>76.19</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="res">
<div style="padding:10px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">3.1 Results</font>
</div>
<div style="text-align:justify; line-height:1.8">
<font style="font-style:italic;font-size:16px;color:#2c3393;"> Results are indicated in the table above. All four models appear to have performed better than the naive models by quite a margin, with the Two layer LSTM with 64 nodes and 32 nodes having the lowest error in terms of percentage. This translates to an improvement by 73.27% (LSTM with 64 nodes), 73.94% (LSTM with 32 nodes), 74.19% (LSTM+LSTM with 64 nodes and 32 nodes) and 76.19% (LSTM+LSTM with 32 nodes and 64 nodes). </font>
</div>
<div id="discuss">
<div style="padding:10px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">3.2 Discussions and Recommendations</font>
</div>
<div style="text-align:justify; line-height:1.8">
<font style="font-style:italic;font-size:16px;color:#2c3393;">
<p style="text-align:justify; line-height:1.8">
</p><p>Adding more epochs and allowing the model train even longer would have some benefits. Results could have improved on all four models if the <code>patience</code> and the <code>min_delta</code> were relaxed.</p>
My recommendation is to include more technical data in the dataset. Based on industry knowledge, irridiance is one of the main drivers of forecasting solar generation. I would expect that including this as a feature would drastically improve the already impressive model results. Similarly, adding power grid data such as power line capacity and degradation, solar panel angle, may improve in each models accuracy.
<p></p>
<p style="text-align:justify; line-height:1.8">
Moving forward, I would want to explore different types of architectures. Similar journal articles suggested using an LSTM-CNN and/or a CNN-LSTM architectures. These two types of models capture not only the temporal data (LSTM) but also the spatial element (CNN). In addition, using a CNN to include images of the panels may improve the models accuracy. as this may capture the overall health of the panel.
</p>
</font><p><font style="font-style:italic;font-size:16px;color:#2c3393;"></font></p>
</div>
<div id="summary">
<div style="padding:3px;">
<font style="font-weight:bold;font-size:20px;color:#2c3393;">4. Summary and Main Learning Points</font>
</div>
<div id="sum">
<div style="padding:10px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">4.1 Summary</font>
</div>
<div style="text-align:justify; line-height:1.8">
<p><font style="font-style:italic;font-size:16px;color:#2c3393;"> The main objective of the study was to apply deep learning models to forecast solar power supply generation. The data collected was from two online sources, the Wholesale Electrcity Spot Market and Weather Underground. Actual plant generation was obtained from the Wholesale Electricity Spot Market and 13 locational temperature data (Clark International Airport) was collected from Weather Underground. Next, domain knowledge was utilized in the preprocessing data to impute missing data. Here, two forms of benchmarks were idenfied, one was an industry agnostic standard while another error was sourced through consultation of industry experts. Afterwhich, a total of 4 different LSTM architecures were tested and all seem to have beaten both the industry agnostic and industry standard errors. Dropouts and Recurrent Dropouts were utilized during training as fine tuning of the model. In addition, ModelCheckpoints and EarlyStopping was implemented during the training to monitor the output and reduce the runtime. For the results, the 2 layer LSTM with 32 nodes and 64 nodes had the best improvement of 76.19%, from an 12.01% error to 2.86% error. </font></p>
</div>
<div id="main">
<div style="padding:10px;">
<font style="font-weight:bold;font-size:15px;color:#2c3393;">4.2 Main Learning Points</font>
</div>
<div style="text-align:justify; line-height:1.8">
<p><font style="font-style:italic;font-size:16px;color:#2c3393;"> <b>The main role of domain knowledge and expertise can be augmented with data science and machine learning.</b></font></p><font style="font-style:italic;font-size:16px;color:#2c3393;">
<p style="text-align:justify; line-height:1.5;">
</p><ul>
<li>The class has taught me the fundamentals of machine learning and deep learning algorithms, such as MLP, Convolutional, to Recurrent neural networks. However, what I discovered during this process is that domain knowledge influences and augments the data science flow. Yes, we may have developed the fundamentals of understanding deep learning techniques but the true potential of an algorithm can be truly harnessed only when some form of domain knowledge is utilized.</li>
</ul>
<p></p>
<p style="text-align:justify; line-height:1.5">
</p><ul>
<li>Industry heuristics can improve the data science pipeline from the feature engineering, benchmarking, model selection and hyperparameter turing. That with prior knowledge on the topic at hand can improve on the accuracy of the resulting model.</li>
</ul>
<p></p>
<p style="text-align:justify; line-height:1.5">
</p><ul>
<li>On the contrary, having industry knowledge can allow me to think more critical with regards to other peoples models (whether in journals or at the office), both from the machine learning and technical perspective.</li>
</ul>
<p></p>
<p style="text-align:justify; line-height:1.5">
</p><ul>
<li>Lastly, one may know the inner workings of the model and know how to implement the model, however with domain knowledge, one will also know how to ask the right questions. Questions relating to (1) business value, on how to extract more value from a model, and/or (2) how can we improve or build on the model. Essentially asking what are the next steps, and how can we improve on this.</li>
</ul>
<p></p>
<b>Not really data science related but: tap the industry the topic is related about. You do not know everything in an industry so leverage on the network to figure out things</b>
<p style="text-align:justify; line-height:1.5">
</p><ul>
<li>Even if I was already in the energy industry, I was not particularly familiar with renewable energy forecasting and the standard protocols. If my groupmate and I were not familiar with the industry, it would have been very difficult for us to verify protocols. However, since I am blessed with very talented people from the industry, a quick 5 minute call was all we needed to verify certain aspect of the industry.</li>
</ul>
<p></p>
<p style="text-align:justify; line-height:1.5;font-weight:bold">
Find a field/aspect of data science that you’re interested in, stick to it, build on it and fix it!
</p>
<p style="text-align:justify; line-height:1.5">
</p><ul>
<li>From the numerous of talks I have listened in this class, it was already ingrained to me that data science is applicable to almost every industry, and as aspiring data scientists it may be difficult to hone in into a certain field or aspect. For me, I find joy when I see the application of data science to the energy sector as I have experienced and seen where the holes in the analytics are. Now, I have the fundamental skillset to cover up and fix these holes.</li>
</ul>
<p></p>
</font><p><font style="font-style:italic;font-size:16px;color:#2c3393;"></font></p>
</div>



</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>